// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type City struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int32              `json:"id"`
	Firstname string             `json:"firstname"`
	Lastname  string             `json:"lastname"`
	Birthdate pgtype.Date        `json:"birthdate"`
	Sex       string             `json:"sex"`
	Interests pgtype.Text        `json:"interests"`
	CityID    int32              `json:"city_id"`
	RoleID    int32              `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserRole struct {
	ID   int32  `json:"id"`
	Role string `json:"role"`
}
