logger:
  level: info

storage:
  type: sql #[memory, sql] if sql, then dsn is required
  dsn: postgres://root:123@db:5432/peepl?sslmode=disable
  migrations_dir: db/migration

httpserver:
  host: 0.0.0.0
  port: 8080
